# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Grantimatter Iris Rev 3'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["keebio/iris/rev3"]'
